authentication/urls.py
from django.urls import path

from authentication.views import (
    login, auth_get, logout, register, registration_success,
    forgot_password, user_profile, update_user_profile,
    activate_user, activation_success, reset_password, change_password_page,
    change_password, password_change_success
)


urlpatterns = [
    path('login/', login, name="login"),
    path('logout/', logout, name="logout"),
    path('auth/', auth_get, name="auth_get"),
    path('register/', register, name="register"),
    path('register-success/', registration_success, name="registration_success"),
    path('activate-user/<str:uidb64>/<str:token>/', activate_user, name="activate_user"),
    path('activation-success/', activation_success, name="activation-success"),
    path('forgot-password/', forgot_password, name="forgot_password"),
    path('reset-password/', reset_password, name="reset_password"),
    path('change-password/<int:pk>/', change_password, name="change_password"),
    path('change-password-page/<str:uidb64>/<str:token>/', change_password_page, name="change_password_page"),
    path('password-change-success/', password_change_success, name="password_change_success"),
    path('profile/', user_profile, name="user_profile"),
    path('update-user-profile/', update_user_profile, name="update_user_profile")
]

app_name = "authentication"

estore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import home

urlpatterns = [
    path('', home, name="home"),
    path('authentication/', include('authentication.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/models.py
from django.db import models

from authentication.utils import upload_path


class Profile(models.Model):
    user = models.OneToOneField('auth.User', on_delete=models.CASCADE)
    telephone_number = models.CharField(max_length=14, null=True)
    photo = models.ImageField(upload_to=upload_path, blank=True, null=True)

    def __str__(self):
        return f"{self.user.get_full_name()} - <{self.user.email}>"

authentication/forms.py
from django import forms
from django.contrib.auth import get_user_model

from authentication.models import Profile


User = get_user_model()


class LoginForm(forms.Form):
    """
    Form for user login validation
    """
    username = forms.EmailField()
    password = forms.CharField()


class RegistrationForm(forms.ModelForm):
    """
    Form for user registration validation
    """
    password1 = forms.CharField()
    password2 = forms.CharField()

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2')

    def clean_password2(self):
        """
        Return any of the passwords if password1 and password2 are equal,
        Raise ValidationError otherwise
        :return:
        """
        data = self.cleaned_data
        if data['password1'] != data['password2']:
            raise forms.ValidationError("Passwords don't match")

        return data['password1']


class ProfileForm(forms.Form):
    first_name = forms.CharField(max_length=150)
    last_name = forms.CharField(max_length=150)
    photo = forms.ImageField(required=False)
    phone_number = forms.CharField(max_length=14)
    password1 = forms.CharField(required=False)
    password2 = forms.CharField(required=False)

    def clean_password1(self):
        """
        Valid Passwords and make sure they're equal
        :return:
        """
        data = self.cleaned_data
        if data.get("password1") or data.get("password2"):
            if data.get("password1") != data.get("password2"):
                return False
        return True

    def update(self):
        profile = Profile.objects.update(
            telephone_number = self.cleaned_data.get("phone_number"),
            photo=self.cleaned_data.get("photo")
        )
        profile.save()

authentication/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model
from django.contrib.auth import login as _login
from django.contrib.auth import logout as _logout
from django.contrib.auth import authenticate
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_decode
from django.http import JsonResponse
from django.urls import reverse

from authentication.forms import LoginForm, RegistrationForm, ProfileForm
from authentication.models import Profile
from authentication.utils import generate_activation_url
from authentication import constants
from authentication.utils import account_activation_token


# TODO: 1. Implement User Registration with Email Activation Link (AuthToken) generation
# TODO: 2. Implement Password Reset with Email Reset Link (PasswordResetToken) generation


User = get_user_model()


def auth_get(request):
    """
    Returns the template for user authentication (login/registration) - auth.html
    :param request:
    :return:
    """
    template = "authentication/auth.html"
    login_form = LoginForm()
    registration_form = RegistrationForm()
    context = {
        "login_form": login_form,
        "registration_form": registration_form
    }
    return render(request, template, context)


def login(request, user=None, next=None):
    """
    Authenticate and login a user, returning the homepage or a redirect(next) url
    :param request:
    :param user:
    :param next:
    :return:
    """
    if user:
        _login(request, user)
        if next:
            return redirect(next)
        else:
            return redirect("home")

    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")

            user = authenticate(username=username, password=password)
            next_url = next or request.GET.get('next')
            if user is not None:
                _login(request, user)
                if next_url:
                    return redirect(next_url)
                else:
                    return redirect("home")
            else:
                messages.error(request, "Invalid username or password!")
                return redirect("authentication:auth_get")

    return redirect("authentication:auth_get")


def logout(request):
    """
    Log user out and clear all sessions
    :param request:
    :return:
    """
    _logout(request)
    next_url = request.GET.get("next")
    if next_url:
        return redirect(next_url)
    else:
        return redirect("home")


def register(request):
    """
    Sign up a user
    :param request:
    :return:
    """
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        phone = request.POST.get("phone")
        if form.is_valid():
            user = form.save(commit=False)
            user.email = form.cleaned_data.get("username")
            user.set_password(form.cleaned_data.get("password1"))
            user.is_active = False
            user.save()
            profile = Profile.objects.create(
                user=user,
                telephone_number=phone
            )
            profile.save()
            url_name = "authentication:activate_user"
            activation_link = generate_activation_url(request, user, url_name)
            message_body = constants.ACCOUNT_ACTIVATION_MESSAGE.format(activation_link=activation_link)
            mailing_list = [user.email]
            send_mail("FreshCollections", message_body, "admin@freshcollections.com", mailing_list)
            user.backend = "authentication.backend.EmailAuthBackend"
            _login(request, user) # , backend="authentication.backend.EmailAuthBackend")
            next_url = request.GET.get("next")
            return redirect("authentication:registration_success")
        else:
            import pdb; pdb.set_trace();

    return redirect("authentication:auth_get")


def activate_user(request, uidb64, token):
    """
    Validate User token and activate user on clicking on activation link
    :param request:
    :param uidb64:
    :param token:
    :return:
    """
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        user.backend = "authentication.backend.EmailAuthBackend"
        _login(request, user)
        return redirect("authentication:activation-success")
    else:
        import pdb; pdb.set_trace()


def activation_success(request):
    """
    Return activation success page
    :param request:
    :return:
    """
    template = "authentication/activation-success.html"
    context = {}
    return render(request, template, context)


def registration_success(request):
    """
    Returns the template for the registration success page
    :param request:
    :return:
    """
    if request.user.is_anonymous:
        return redirect("authentication:auth_get")
    else:
        template = "authentication/registration-success.html"
        context = {}
        return render(request, template, context)


def forgot_password(request):
    template = "authentication/forgot-password.html"
    context = {}
    return render(request, template, context)


def reset_password(request):
    if request.method == "POST":
        email = request.POST.get("email")
        try:
            user = User.objects.get(email=email)
            url_name = "authentication:change_password_page"
            password_reset_link = generate_activation_url(request, user, url_name)
            message_body = constants.PASSWORD_RESET_MESSAGE.format(email=email, password_link=password_reset_link)
            mailing_list = [email]
            send_mail("Password Reset Request", message_body, "admin@freshcollections.com", mailing_list)
            template = "authentication/password-link-sent.html"
            context = {}
            return render(request, template, context)
        except User.DoesNotExist:
            error_data = {
                "user_exist": False
            }
            return JsonResponse(error_data, safe=False, content_type="application/json")


def change_password_page(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (ValueError, TypeError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        template = "authentication/change-password.html"
        post_url = reverse("authentication:change_password", args=[uid])
        context = {"post_url": post_url}
        return render(request, template, context)


def change_password(request, pk):
    if request.method == "POST":
        password = request.POST.get("password")
        user = User.objects.get(pk=pk)
        user.set_password(password)
        user.save()
        return redirect("authentication:password_change_success")


def password_change_success(request):
    template = "authentication/password-change-success.html"
    context = {}
    return render(request, template, context=context)


@login_required
def user_profile(request):
    template = "authentication/user-profile.html"
    profile = Profile.objects.get(user=request.user)
    context = {
        "profile": profile,
        "page_title": "Profile info",
        # "page_description": "Update your profile details below",
    }
    return render(request, template, context)


@login_required
def update_user_profile(request, pk):
    profile = get_object_or_404(Profile, pk=pk)
    if request.user is profile.user:
        form = ProfileForm(request.POST)
        if form.is_valid():
            password = form.cleaned_data.get("password1")
            form.update()
            request.user.set_password(password)
        else:
            messages.error(request, "An Internal Server Error Occurred")
            return redirect("user-profile")

templates/authentication/activation-success.html
{% extends 'base.html' %}

{% block content %}

<div class="container py-4 py-lg-5 my-4">
    <div class="row justify-content-center">
        <div class="col-lg-8 col-md-10">
          <h2 class="h3 mb-4">Account Activation Successful</h2>
          <p class="font-size-md">You have successfully activated your account.</p>
          <div class="card py-2 mt-4">
            <form class="card-body needs-validation" novalidate>
              <a href="{% url 'home' %}" class="btn btn-primary" type="submit"><i class="czi-arrow-left"></i> Continue Shopping</a>
            </form>
          </div>
        </div>
    </div>
</div>


{% endblock %}

templates/authentication/auth.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container py-4 py-lg-5 my-4">
      <div class="row">
        <div class="col-md-6">
          <div class="card border-0 box-shadow">
            <div class="card-body">
              <h2 class="h4 mb-1">Sign in</h2>
              <div class="py-3">
                <h3 class="d-inline-block align-middle font-size-base font-weight-semibold mb-2 mr-2">With social account:</h3>
                <div class="d-inline-block align-middle"><a class="social-btn sb-google mr-2 mb-2" href="#" data-toggle="tooltip" title="Sign in with Google"><i class="czi-google"></i></a><a class="social-btn sb-facebook mr-2 mb-2" href="#" data-toggle="tooltip" title="Sign in with Facebook"><i class="czi-facebook"></i></a><a class="social-btn sb-twitter mr-2 mb-2" href="#" data-toggle="tooltip" title="Sign in with Twitter"><i class="czi-twitter"></i></a></div>
                {% if messages|length > 0 %}
                  <div class="errornote text-center text-danger font-size-sm">{% for message in messages %}{{ message }}{% endfor %}</div>
                {% endif %}
              </div>
              <hr>
              <h3 class="font-size-base pt-4 pb-2">Or using form below</h3>
              <form method="POST" class="needs-validation" action="{% url 'authentication:login' %}" autocomplete="off" novalidate>
                  {% csrf_token %}
                <div class="input-group-overlay form-group">
                  <div class="input-group-prepend-overlay"><span class="input-group-text"><i class="czi-mail"></i></span></div>
                  <input name="{{ login_form.username.name }}" id="{{ login_form.username.id_for_label }}" class="form-control prepended-form-control" type="email" placeholder="Email" required>
                </div>
                <div class="input-group-overlay form-group">
                  <div class="input-group-prepend-overlay"><span class="input-group-text"><i class="czi-locked"></i></span></div>
                  <div class="password-toggle">
                    <input name="{{ login_form.password.name }}" id="{{ login_form.password.id_for_label }}" class="form-control prepended-form-control" type="password" placeholder="Password" required>
                    <label class="password-toggle-btn">
                      <input class="custom-control-input" type="checkbox"><i class="czi-eye password-toggle-indicator"></i><span class="sr-only">Show password</span>
                    </label>
                  </div>
                </div>
                <div class="d-flex flex-wrap justify-content-between">
                  <div class="custom-control custom-checkbox">
                    <input class="custom-control-input" type="checkbox" checked id="remember_me">
                    <label class="custom-control-label" for="remember_me">Remember me</label>
                  </div><a class="nav-link-inline font-size-sm" href="{% url 'authentication:forgot_password' %}">Forgot password?</a>
                </div>
                <hr class="mt-4">
                <div class="text-right pt-4">
                  <button class="btn btn-primary" type="submit"><i class="czi-sign-in mr-2 ml-n21"></i>Sign In</button>
                </div>
              </form>
            </div>
          </div>
        </div>
        <div class="col-md-6 pt-4 mt-3 mt-md-0">
          <h2 class="h4 mb-3">No account? Sign up</h2>
          <p class="font-size-sm text-muted mb-4">Registration takes less than a minute but gives you full control over your orders.</p>
          <form method="POST" action="{% url 'authentication:register' %}" class="needs-validation" autocomplete="off" novalidate id="signup">
            {% csrf_token %}
            <div class="row">
              <div class="col-sm-6">
                <div class="form-group">
                  <label for="{{ registration_form.first_name.id_for_label }}">First Name</label>
                  <input placeholder="eg. John" minlength="3" name="{{ registration_form.first_name.name }}" class="form-control" type="text" required id="{{ registration_form.first_name.id_for_label }}">
                  <div class="invalid-tooltip">Please enter a valid first name! (3 or more characters)</div>
                    <div class="valid-tooltip">Looks good!</div>
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                  <label for="{{ registration_form.last_name.id_for_label }}">Last Name</label>
                  <input placeholder="eg. Doe" minlength="3" name="{{ registration_form.last_name.name }}" class="form-control" type="text" required id="{{ registration_form.last_name.id_for_label }}">
                  <div class="invalid-tooltip">Please enter a valid name last name! (3 or more characters)</div>
                    <div class="valid-tooltip">Looks good!</div>
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                  <label for="{{ registration_form.username.id_for_label }}">E-mail Address</label>
                  <input placeholder="johndoe@email.com" name="{{ registration_form.username.name }}" class="form-control" type="email" required id="{{ registration_form.username.id_for_label }}">
                  <div class="invalid-tooltip">Please enter a valid email!</div>
                    <div class="valid-tooltip">Looks good!</div>
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                    <label for="id_phone">Phone Number</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <div class="input-group-text">+233</div>
                        </div>
                      <input placeholder="502224321" name="phone" class="form-control" type="tel" min="0" minlength="9" id="id_phone">
                    </div>
                    <small class="form-text text-muted">Optional: You can leave this field out and fill later</small>
                    <div class="invalid-tooltip">Please enter a valid phone number!</div>
                    <div class="valid-tooltip">Looks good!</div>
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                  <label for="{{ registration_form.password1.id_for_label }}">Password</label>
                  <input name="{{ registration_form.password1.name }}" class="form-control" type="password" required id="{{ registration_form.password1.id_for_label }}">
                  <div class="invalid-tooltip">Please enter a valid password!</div>
                    <div class="invalid-tooltip">Your password must be 8-20 characters long, contain letters and numbers, and must not contain spaces, special characters, or emoji.</div>
                    <small id="password-help-text" class="form-text text-muted">Your password must be 8-20 characters long, contain letters and numbers, and must not contain spaces, special characters, or emoji.</small>
                    <div class="valid-tooltip">Looks good!</div>
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                  <label for="{{ registration_form.password2.id_for_label }}-confirm">Confirm Password</label>
                  <input name="{{ registration_form.password2.name }}" class="form-control" type="password" required id="{{ registration_form.password2.id_for_label }}-confirm">
                  <div id="password-valid-div" class="valid-tooltip">Looks good</div>
                    <div id="password-invalid-div" class="invalid-tooltip">Password mismatch</div>
                </div>
              </div>
            </div>
            <div class="text-right">
              <button class="btn btn-primary" type="submit"><i class="czi-user mr-2 ml-n1"></i>Sign Up</button>
            </div>
          </form>
        </div>
      </div>
    </div>
{% endblock content %}

{% block script %}
    <script src="{% static 'js/utils.js' %}"></script>
    <script>
        const password2ErrorText = document.querySelector("#password-invalid-div");
        const password2ValidText = document.querySelector("#password-valid-div");
        const passwordHelpText = document.querySelector("#password-help-text")

        const password1Input = signUpForm.password1;
        const password2Input = signUpForm.password2;

        signUpForm.onsubmit = () => {
            if (!validatePassword(signUpForm.password1.value)){
                signUpForm.password1.setCustomValidity("Invalid")
                passwordHelpText.style.display = "none"
                signUpForm.password1.addEventListener("input", validatingPassword)
                validatePasswordMatch(password1Input, password2Input)
                return false;
            }
        }
    </script>
{% endblock %}

templates/authentication/change-password.html
{% extends 'base.html' %}


{% block content %}

<div class="container py-4 py-lg-5 my-4">
  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-10">
      <h2 class="h3 mb-4">Change Your Password</h2>
      <p class="font-size-md">Make sure you set a very strong password which meets the following pattern</p>
      <ol class="list-unstyled font-size-md">
        <li><span class="text-primary mr-2">1.</span>Your password must be at least 8 characters long.</li>
        <li><span class="text-primary mr-2">2.</span>It must contain alphanumeric characters with at least 1 <em>UPPER</em> and <em>LOWER</em> character each.</li>
        <li><span class="text-primary mr-2">3.</span>It cannot emojis.</li>
      </ol>
      <div class="card py-2 mt-4">
        <form autocomplete="off" method="POST" action="{{ post_url }}" class="card-body needs-validation" novalidate>
          {% csrf_token %}
            <div class="form-group">
            <label for="id_password">Enter your new Password</label>
            <div class="password-toggle">
                <input name="password" class="form-control" type="password" id="id_password" required>
                <label class="password-toggle-btn">
                    <i class="czi-eye password-toggle-indicator"></i>
                </label>
            </div>
            <div class="invalid-feedback">Please provide valid password.</div>
            <div class="valid-feedback">Looks strong and secured.</div>
          </div>
          <button class="btn btn-primary" type="submit">Get new password</button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/authentication/forgot-password.html
{% extends 'base.html' %}


{% block content %}

<div class="container py-4 py-lg-5 my-4">
  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-10">
      <h2 class="h3 mb-4">Forgot your password?</h2>
      <p class="font-size-md">Change your password in three easy steps. This helps to keep your new password secure.</p>
      <ol class="list-unstyled font-size-md">
        <li><span class="text-primary mr-2">1.</span>Fill in your email address below.</li>
        <li><span class="text-primary mr-2">2.</span>We'll email you a temporary code.</li>
        <li><span class="text-primary mr-2">3.</span>Use the code to change your password on our secure website.</li>
      </ol>
      <div class="card py-2 mt-4">
        <form method="POST" action="{% url 'authentication:reset_password' %}" class="card-body needs-validation" novalidate>
          {% csrf_token %}
            <div class="form-group">
            <label for="recover-email">Enter your email address</label>
            <input name="email" class="form-control" type="email" id="recover-email" required>
            <div class="invalid-feedback">Please provide valid email address.</div>
          </div>
          <button class="btn btn-primary" type="submit">Get new password</button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/authentication/user-profile.html
{% extends 'authentication/user-base.html' %}
{% load static %}

{% block detail_content %}
    <div class="container pb-5 mb-2 mb-md-3">
      <div class="row">
      <!-- Sidebar -->
      {% include 'components/user-sidebar.html' %}

        <!-- Content  -->
        <section class="col-lg-8">
          <!-- Toolbar-->
          <div class="d-none d-lg-flex justify-content-between align-items-center pt-lg-3 pb-4 pb-lg-5 mb-lg-3">
            <h6 class="font-size-base text-light mb-0">Update you profile details below:</h6>
            <a class="btn btn-primary btn-sm" href="{% url 'authentication:logout' %}">
                <i class="czi-sign-out mr-2"></i>Sign out
            </a>
          </div>
          <!-- Profile form-->
          <form id="profileForm" method="POST" class="needs-validation" autocomplete="off" novalidate action="{% url 'authentication:update_user_profile' %}">
            {% csrf_token %}
              <div class="bg-secondary rounded-lg p-4 mb-4">
              <div class="media align-items-center">
                  {% if profile.photo %}
                      <img src="img/shop/account/avatar.jpg" width="90" alt="Susan Gardner">
                  {% else %}
                      <i class="font-size-xl czi-user-circle"></i>
                  {% endif %}
                <div class="media-body pl-3">
                  <button class="btn btn-light btn-shadow btn-sm mb-2" type="button"><i class="czi-loading mr-2"></i>Change avatar</button>
                  <div class="p mb-0 font-size-ms text-muted">Upload JPG, GIF or PNG image. 300 x 300 required.</div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-sm-6">
                <div class="form-group">
                  <label for="account-fn">First Name</label>
                  <input class="form-control" type="text" id="account-fn" value="{{ profile.user.first_name }}">
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                  <label for="account-ln">Last Name</label>
                  <input class="form-control" type="text" id="account-ln" value="{{ profile.user.last_name }}">
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                  <label for="account-email">Email Address</label>
                  <input class="form-control" type="email" id="account-email" value="{{ profile.user.email }}" disabled>
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                  <label for="account-phone">Phone Number</label>
                  <input class="form-control" type="text" id="account-phone" value="+233 {{ profile.telephone_number }}" required>
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                  <label for="account-pass">New Password</label>
                  <div class="password-toggle">
                    <input name="password1" class="form-control" type="password" id="account-pass">
                    <label class="password-toggle-btn">
                      <input class="custom-control-input" type="checkbox"><i class="czi-eye password-toggle-indicator"></i><span class="sr-only">Show password</span>
                    </label>
                  </div>
                    <small id="password-help-text" class="form-text text-muted">Your password must be 8-20 characters long, contain letters and numbers, and must not contain spaces, special characters, or emoji.</small>
                    <div class="valid-tooltip">Looks good!</div>
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                  <label for="account-confirm-pass">Confirm Password</label>
                  <div class="password-toggle">
                    <input name="password2" class="form-control" type="password" id="account-confirm-pass">
                    <label class="password-toggle-btn">
                      <input class="custom-control-input" type="checkbox"><i class="czi-eye password-toggle-indicator"></i><span class="sr-only">Show password</span>
                    </label>
                  </div>
                    <div id="password-valid-div" class="valid-tooltip">Looks good</div>
                    <div id="password-invalid-div" class="invalid-tooltip">Password mismatch</div>
                </div>
              </div>
              <div class="col-12">
                <hr class="mt-2 mb-3">
                <div class="d-flex flex-wrap justify-content-between align-items-center">
                  <div class="custom-control custom-checkbox d-block">
                    <input class="custom-control-input" type="checkbox" id="subscribe_me" checked>
                    <label class="custom-control-label" for="subscribe_me">Subscribe me to Newsletter</label>
                  </div>
                  <button class="btn btn-primary mt-3 mt-sm-0" type="submit">Update profile</button>
                </div>
              </div>
            </div>
          </form>
        </section>
      </div>
    </div>

{% endblock %}

{% block script %}
{#    TODO: Fix bug with the implementation of password match validation with an error text #}
    <script src="{% static 'js/utils' %}"></script>
    <script>
        const profileForm = document.querySelector("#profileForm");

        const password2ErrorText = document.querySelector("#password-invalid-div");
        const password2ValidText = document.querySelector("#password-valid-div");
        const passwordHelpText = document.querySelector("#password-help-text")

        const password1Input = profileForm.password1;
        const password2Input = profileForm.password2;

        profileForm.onsubmit = () => {
            console.log("Submiting")
            if (!validatePassword(password1Input.value)) {
                password1Input.setCustomValidity("Invalid")
                passwordHelpText.style.display = "none"
                password1Input.addEventListener("input", validatingPassword)
                validatePasswordMatch(password1Input, password2Input)
                return false;
            }
        }
    </script>
{% endblock %}